version: '3.8'

services:
  postgres:
    container_name: 'postgres'
    restart: always
    image: 'postgres:12'
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  redis:
    container_name: 'redis'
    restart: always
    image: 'redis:latest'
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/data'

volumes:
  postgres:
  redis:
